---
- name: install headnode packages
  apt: name={{item}} state=present install_recommends=true
  with_items:
    - screen
    - nfs-kernel-server
    - tcpdump
    - nmap
    - locate
    - isc-dhcp-server
    - clustershell

- include_tasks: nis_as_server.yaml
