---
- name: Set cluster node hostname
  ansible.builtin.hostname:
    name: "{{ inventory_hostname }}"

- name: Add cluster nodes to hosts file
  ansible.builtin.lineinfile:
    path: /etc/hosts
    regexp: '.*{{ item }}$'
    line: "{{ hostvars[item].ansible_host }} {{item}}"
    state: present
  when: hostvars[item].ansible_host is defined
  with_items: "{{ groups.all }}"